version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3e4r@#$$
    ports:
      - 1401:1433
    restart: unless-stopped
  store-api:
    image: thiagoberrutti/store-api
    ports: 
      - 5000:5000
    environment:
      - PORT=5000
      - StoreDbSQLServerConnectionStringSettings__DataSource=sqlserver,1433
    restart: unless-stopped
    depends_on:
      - sqlserver

# NETWORK: docker network create store-network
# DATABASE: docker run -d -p 1401:1433 --name sqlserver --net store-network -e ACCEPT_EULA=Y -e SA_PASSWORD=1q2w3e4r@#$ mcr.microsoft.com/mssql/server:latest
# API: docker run -d -p 5000:5000 --name store-api --net store-network -e PORT=5000 -e ASPNETCORE_ENVIRONMENT=Development -e StoreDbSQLServerConnectionStringSettings__DataSource=sqlserver,1433 thiagoberrutti/store-api

